# Generated by Django 5.1.7 on 2025-07-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_category_moment_if_alter_image_moment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='if',
            old_name='content',
            new_name='if_content',
        ),
    ]
