# Generated by Django 5.2.4 on 2025-07-10 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0004_alter_if_moment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTop3Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateTimeField(auto_now=True)),
                ('keywords', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.category')),
            ],
            options={
                'unique_together': {('week_start', 'category')},
            },
        ),
    ]
