# Generated by Django 5.2.4 on 2025-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0005_weeklytop3keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytop3keyword',
            name='week_start',
            field=models.DateField(),
        ),
    ]
